### ISSUE TITLE
invalid-read-syntax "integer, radix 2"

### ISSUE THREAD

**Issue by manuel-uberti** [wbolster/emacs-balanced-windows#3]
Hi,

first of all thanks for coming up with this package. I have a problem using it, though. After installing it from MELPA, I'm getting this error:

```
Debugger entered--Lisp error: (invalid-read-syntax "integer, radix 2")
  read(#<buffer  *load*>)
  eval-buffer(#<buffer  *load*> nil "/home/manuel/.emacs.d/elpa/balanced-windows-201909..." nil t)  ; Reading at buffer position 1135
  load-with-code-conversion("/home/manuel/.emacs.d/elpa/balanced-windows-201909..." "/home/manuel/.emacs.d/elpa/balanced-windows-201909..." nil t)
  require(balanced-windows)
  (progn (require 'balanced-windows))
  eval((progn (require 'balanced-windows)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

A simple recipe to reproduce the error:

- `emacs -Q`
- `M-x package-initialize`
- `M-x toggle-debug-on-error`
- add `(require 'balanced-windows)` in the `*scratch*` buffer
- put point after `)` and hit <kbd>C-x C-e</kbd>

I am using GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2019-09-02.

**Comment by wbolster** [comment]
sorry, this was caused by me making a typo while using the github web editor from my phone... 🙈

#2 fixes it. the next melpa rebuild (every few hours) should solve this for everyone.

**Comment by manuel-uberti** [comment]
Confirmed, fixed after the update. Thank you.
